name: Latest blog post workflow
on:
  push:
    branches:
      - master
  schedule: # Run workflow automatically
    - cron: '0 0 1 * *' # Runs every month 
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: "10"
          remove_duplicates: true
          feed_list: "https://dev.to/feed/samayun,https://samayun.medium.com/feed,https://stackoverflow.com/feeds/user/12932846"
# Exclude stackOverflow feeds : https://stackoverflow.com/feeds/user/12932846
