name: GitHub-Profile-3D-Contribution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@main
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_3D_GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name samayun
          git config user.email samayun.m.chowdhury@gmail.com
          git add -A .
          git commit -m "chore(ci/cd): Personal 3d Contributions images"
          git push
